<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class initItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('items')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('items')->insert([
            [
            "name" => "cloth",
            "description" => "description for testing..... ",
            "image" => "/images/cloth.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "crocs",
            "description" => "description for testing..... ",
            "image" => "/images/crocs.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "jacket",
            "description" => "description for testing..... ",
            "image" => "/images/jacket.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "shoes",
            "description" => "description for testing..... ",
            "image" => "/images/shoes.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "t-shirt",
            "description" => "description for testing..... ",
            "image" => "/images/tshirt-img.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big cloth",
            "description" => "description for testing..... ",
            "image" => "/images/cloth.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big crocs",
            "description" => "description for testing..... ",
            "image" => "/images/crocs.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big jacket",
            "description" => "description for testing..... ",
            "image" => "/images/jacket.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big shoes",
            "description" => "description for testing..... ",
            "image" => "/images/shoes.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big t-shirt",
            "description" => "description for testing..... ",
            "image" => "/images/tshirt-img.jpg",
            "user_id" => "1",
            "category_id" =>"1",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "camping",
            "description" => "description for testing..... ",
            "image" => "/images/campgoods.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "tent",
            "description" => "description for testing..... ",
            "image" => "/images/tent.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "swimring",
            "description" => "description for testing..... ",
            "image" => "/images/swimring.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "umbrella",
            "description" => "description for testing..... ",
            "image" => "/images/umbrella.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "xmastree",
            "description" => "description for testing..... ",
            "image" => "/images/xmastree.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big camping",
            "description" => "description for testing..... ",
            "image" => "/images/campgoods.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big tent",
            "description" => "description for testing..... ",
            "image" => "/images/tent.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big swimring",
            "description" => "description for testing..... ",
            "image" => "/images/swimring.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big umbrella",
            "description" => "description for testing..... ",
            "image" => "/images/umbrella.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big xmastree",
            "description" => "description for testing..... ",
            "image" => "/images/xmastree.jpg",
            "user_id" => "1",
            "category_id" =>"3",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mug cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "lipstick",
            "description" => "description for testing..... ",
            "image" => "/images/lipstick.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "necklace",
            "description" => "description for testing..... ",
            "image" => "/images/necklace.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "perfume",
            "description" => "description for testing..... ",
            "image" => "/images/perfume.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "1",
            "category_id" =>"2",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
// user2
            [
            "name" => "cloth",
            "description" => "description for testing..... ",
            "image" => "/images/cloth.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "crocs",
            "description" => "description for testing..... ",
            "image" => "/images/crocs.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "jacket",
            "description" => "description for testing..... ",
            "image" => "/images/jacket.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "shoes",
            "description" => "description for testing..... ",
            "image" => "/images/shoes.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "t-shirt",
            "description" => "description for testing..... ",
            "image" => "/images/tshirt-img.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "camping",
            "description" => "description for testing..... ",
            "image" => "/images/campgoods.jpg",
            "user_id" => "2",
            "category_id" =>"6",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "tent",
            "description" => "description for testing..... ",
            "image" => "/images/tent.jpg",
            "user_id" => "2",
            "category_id" =>"6",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "swimring",
            "description" => "description for testing..... ",
            "image" => "/images/swimring.jpg",
            "user_id" => "2",
            "category_id" =>"6",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "umbrella",
            "description" => "description for testing..... ",
            "image" => "/images/umbrella.jpg",
            "user_id" => "2",
            "category_id" =>"6",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "xmastree",
            "description" => "description for testing..... ",
            "image" => "/images/xmastree.jpg",
            "user_id" => "2",
            "category_id" =>"6",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "2",
            "category_id" =>"5",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "2",
            "category_id" =>"5",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "2",
            "category_id" =>"5",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mug cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "2",
            "category_id" =>"5",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "2",
            "category_id" =>"5",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "lipstick",
            "description" => "description for testing..... ",
            "image" => "/images/lipstick.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "necklace",
            "description" => "description for testing..... ",
            "image" => "/images/necklace.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "perfume",
            "description" => "description for testing..... ",
            "image" => "/images/perfume.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "2",
            "category_id" =>"4",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
// user3
            [
            "name" => "cloth",
            "description" => "description for testing..... ",
            "image" => "/images/cloth.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "crocs",
            "description" => "description for testing..... ",
            "image" => "/images/crocs.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "jacket",
            "description" => "description for testing..... ",
            "image" => "/images/jacket.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "shoes",
            "description" => "description for testing..... ",
            "image" => "/images/shoes.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "t-shirt",
            "description" => "description for testing..... ",
            "image" => "/images/tshirt-img.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "camping",
            "description" => "description for testing..... ",
            "image" => "/images/campgoods.jpg",
            "user_id" => "3",
            "category_id" =>"9",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "tent",
            "description" => "description for testing..... ",
            "image" => "/images/tent.jpg",
            "user_id" => "3",
            "category_id" =>"9",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "swimring",
            "description" => "description for testing..... ",
            "image" => "/images/swimring.jpg",
            "user_id" => "3",
            "category_id" =>"9",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "umbrella",
            "description" => "description for testing..... ",
            "image" => "/images/umbrella.jpg",
            "user_id" => "3",
            "category_id" =>"9",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "xmastree",
            "description" => "description for testing..... ",
            "image" => "/images/xmastree.jpg",
            "user_id" => "3",
            "category_id" =>"9",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "3",
            "category_id" =>"8",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "3",
            "category_id" =>"8",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "3",
            "category_id" =>"8",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "mug cup",
            "description" => "description for testing..... ",
            "image" => "/images/cup.jpg",
            "user_id" => "3",
            "category_id" =>"8",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big mixer",
            "description" => "description for testing..... ",
            "image" => "/images/mixer.jpg",
            "user_id" => "3",
            "category_id" =>"8",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "lipstick",
            "description" => "description for testing..... ",
            "image" => "/images/lipstick.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "necklace",
            "description" => "description for testing..... ",
            "image" => "/images/necklace.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "perfume",
            "description" => "description for testing..... ",
            "image" => "/images/perfume.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
            [
            "name" => "big notebook",
            "description" => "description for testing..... ",
            "image" => "/images/notebook.jpg",
            "user_id" => "3",
            "category_id" =>"7",
            "created_at" => NOW(),
            "updated_at" => NOW(),
            ],
        ]);
    }
}
